/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juco_game;

import Elements.Images;
import Elements.barrier;
import Elements.mapa;
import Elements.player;
import Elements.element;
import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author L E D E S M A
 */
public class Inicio extends javax.swing.JFrame {
    player newPlayer;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        
        mapa Mapa1 = new mapa("001");
        
        //Creacion de muros
        
        barrier top = new barrier(Color.BLACK,0,0,800,15,"top");
        barrier right = new barrier(Color.BLACK,785,0,15,500,"rigth");
        barrier left = new barrier(Color.BLACK,0,0,15,500,"left");
        barrier down = new barrier(Color.BLACK,0,485,800,15,"down");
        barrier middle = new barrier(Color.BLACK,0,245,800,15,"middle");
        
        barrier uno = new barrier(Color.BLACK,0,0,50,100,"left");
        barrier dos  = new barrier(Color.BLACK,0,150,50,100,"left");
        
        barrier ultimo = new barrier(Color.BLACK,750,0,50,100,"rigth");
        barrier penultimo  = new barrier(Color.BLACK,750,150,50,100,"rigth");
        
 
        
        //barrier tres = new barrier(Color.BLACK,0,0,,15,"top");

        Mapa1.getMisElementos().add(top);
        Mapa1.getMisElementos().add(right);
        Mapa1.getMisElementos().add(left);
        Mapa1.getMisElementos().add(down);
        Mapa1.getMisElementos().add(middle);
        Mapa1.getMisElementos().add(uno);
        Mapa1.getMisElementos().add(dos);
        Mapa1.getMisElementos().add(ultimo);
        Mapa1.getMisElementos().add(penultimo); 
        
        //Creacion de jugadores
        this.newPlayer = new player(200,"src/pictures/bola1.png",25,115,18,18,"globo_rojo");
        Mapa1.getMisElementos().add(this.newPlayer);
        
        lienzo1.setMiMapa(Mapa1);
        Thread proceso = new Thread(lienzo1);
        this.lienzo1.setActivo(true);
        proceso.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo1 = new juco_game.Lienzo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lienzo1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lienzo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lienzo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        this.setFocusable(true);
        if(evt.getKeyChar() == 'w' || evt.getKeyChar() == 'W'|| evt.getExtendedKeyCode() == KeyEvent.VK_UP){
            if (verificar()== true){
                this.newPlayer.setY(this.newPlayer.getX()-5);
            }
        }else if(evt.getKeyChar() == 'a' || evt.getKeyChar() == 'A'|| evt.getExtendedKeyCode() == KeyEvent.VK_LEFT){
           this.newPlayer.setX(this.newPlayer.getX()-5);
        }else if(evt.getKeyChar() == 's' || evt.getKeyChar() == 'S'|| evt.getExtendedKeyCode() == KeyEvent.VK_DOWN){
           this.newPlayer.setY(this.newPlayer.getY()+5);
        }else if(evt.getKeyChar() == 'd' || evt.getKeyChar() == 'D'|| evt.getExtendedKeyCode() == KeyEvent.VK_RIGHT){
           this.newPlayer.setX(this.newPlayer.getX()+5);
        }
    }//GEN-LAST:event_formKeyPressed
    
    public boolean verificar(){
        boolean respuesta = false ;
        for (element actual:this.lienzo1.getMiMapa().getMisElementos()){
            if (this.newPlayer.getArea().intersects(actual.getArea())){
                respuesta = true;
            } 
        }
        return respuesta;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private juco_game.Lienzo lienzo1;
    // End of variables declaration//GEN-END:variables
}
