/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juco_game;

import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author girveos
 */
public class Inicio_interfaz extends javax.swing.JFrame {
    Clip sonido;
    /**
     * Creates new form Inicio_interfaz
     */
    public Inicio_interfaz() {
        initComponents();
        empezar("src/sounds/main_song.wav");
    }
    public void empezar(String Ruta){
        try{
        this.sonido = AudioSystem.getClip();
        sonido.open(AudioSystem.getAudioInputStream(new File(Ruta)));
        sonido.start();
        } catch(Exception e){
            System.out.println("Error sonido");
        }  
    }
    public void apagar(){
        this.sonido.stop();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cancelarbtn = new javax.swing.JButton();
        comenzarbtn = new javax.swing.JButton();
        back_ground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Cancelarbtn.setBackground(new java.awt.Color(255, 51, 51));
        Cancelarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/cancel.png"))); // NOI18N
        Cancelarbtn.setContentAreaFilled(false);
        Cancelarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelarbtn);
        Cancelarbtn.setBounds(560, 410, 70, 70);

        comenzarbtn.setBackground(new java.awt.Color(51, 255, 51));
        comenzarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/go.png"))); // NOI18N
        comenzarbtn.setContentAreaFilled(false);
        comenzarbtn.setDefaultCapable(false);
        comenzarbtn.setPreferredSize(new java.awt.Dimension(81, 32));
        comenzarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarbtnActionPerformed(evt);
            }
        });
        getContentPane().add(comenzarbtn);
        comenzarbtn.setBounds(240, 410, 64, 64);

        back_ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Juco_interfaz_principal.png"))); // NOI18N
        back_ground.setText("jLabel1");
        getContentPane().add(back_ground);
        back_ground.setBounds(6, 6, 772, 488);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comenzarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarbtnActionPerformed
        // TODO add your handling code here:
        apagar();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }//GEN-LAST:event_comenzarbtnActionPerformed

    private void CancelarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelarbtn;
    private javax.swing.JLabel back_ground;
    private javax.swing.JButton comenzarbtn;
    // End of variables declaration//GEN-END:variables
}
