/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juco_game;

import Elements.Image;
import Elements.barrier;
import Elements.element;
import Elements.mapa;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.util.LinkedList;

/**
 *
 * @author L E D E S M A
 */
public class Lienzo extends javax.swing.JPanel implements Runnable {
    private mapa miMapa;
    private boolean activo;
    /**
     * Creates new form Lienxo
     */
    public Lienzo() {
        initComponents();
        this.activo = false;
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        DibujarFigura(g);
    }
    
    public void DibujarFigura(Graphics g){
            for(element ActualE :this.getMiMapa().getMisElementos()){
                if(ActualE instanceof barrier){
                    Dibujarbarrier(g,(barrier)ActualE);
                }else if(ActualE instanceof Image){
                    dibujarImagen(g,(Image)ActualE);
                }
        }
    }
    public void Dibujarbarrier(Graphics g,barrier elemento){
        g.setColor(elemento.getColor());
        g.fillRect(elemento.getX(),elemento.getY(),elemento.getAncho(),elemento.getAlto());
        
        g.drawRect(elemento.getX(),elemento.getY(),elemento.getAncho(),elemento.getAlto());
        
    }
    public void dibujarImagen(Graphics g,Image laImagen){
    Toolkit t = Toolkit.getDefaultToolkit ();
    java.awt.Image imagen = t.getImage (laImagen.getRuta());
    g.drawImage(imagen,
                laImagen.getX(),
                laImagen.getY(),
                laImagen.getAncho(),
                laImagen.getAlto(),
                this);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the miMapa
     */
    public mapa getMiMapa() {
        return miMapa;
    }

    /**
     * @param miMapa the miMapa to set
     */
    public void setMiMapa(mapa miMapa) {
        this.miMapa = miMapa;
    }

    /**
     * @return the activo
     */
    public boolean isActivo() {
        return activo;
    }

    /**
     * @param activo the activo to set
     */
    public void setActivo(boolean activo) {
        this.activo = activo;
    }

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
